### ISSUE TITLE
opencenter server agent is not always being placed in the Service Nodes container

### ISSUE THREAD

**Issue by willkelly** [rcbops/opencenter#433]

**Comment by willkelly** [comment]
We need to use the same mechanism to get hostname (I recommend socket.getfqdn()) in both agent (task_input.py) and opencenter (whoami in nodes.py in webapp)

We need to detect whether the agent's name would be reported differently and update the node record with the proper name when appropriate.

**Comment by galstrom21** [comment]
Changes have been applied across all 3 repos.. closing issue.

@git-harry: if closed incorrectly please re-open.
