### ISSUE TITLE
Chef Server - OHAI enumerates all LDAP entries causing performance problems

### ISSUE THREAD

**Issue by jcannava** [rcbops/opencenter#436]
http://tickets.opscode.com/browse/OHAI-165

Need to figure out how to disable this in Chef 11.

**Comment by breu** [comment]
notes: http://wiki.opscode.com/display/chef/Disabling+Ohai+Plugins

**Comment by claco** [comment]
Fixed in agent:  https://github.com/rcbops/opencenter-agent/pull/208
