### ISSUE TITLE
Disable Host feature may not work based on hostname

### ISSUE THREAD

**Issue by doublerr** [rcbops/opencenter#445]
https://privatecloudforums.rackspace.com/viewtopic.php?f=4&t=361

This is similar to the issue of how hostnames are leveraged in opencenter. The issue is that depending on the hostnames, openstack may store a different hostname (short vs. FQDN) than opencenter. In the case where they are different, disable host adventure will fail.

**Comment by GeoKM** [comment]
I think if Opencentre could check which type of data the openstack nova environment is using (ie. what appears in "nova-manage service list" and then use that value (short or FQDN) for all nova-manage commands that should fix it 8-)

**Comment by breu** [comment]
moving to https://github.com/rcbops/opencenter-agent/issues/220 and closing this one.
