### ISSUE TITLE
[DE37] Poor error reporting on failed key install for apt repo

### ISSUE THREAD

**Issue by jcannava** [rcbops/opencenter#458]
the script is not checking to see if the key is installed and the process then fails when attempting to 'apt-get update'. A simple check on the return status and an error message would prevent needless debugging.

**Comment by andymcc** [comment]
Although apt-get update should never have been run (since set -e is enabled the failure of apt-key command will kill the script) - I've added a line to make that clear and explicitly exit 1.
https://github.com/rcbops/opencenter-install-scripts/pull/164
