### ISSUE TITLE
[DE42] KVM VM Networking issues with Ubuntu where Kernel > 3.2.x

### ISSUE THREAD

**Issue by metral** [rcbops/opencenter#462]
I discovered that VM Networking in Ubuntu 12.04.2+ where the kernel is > 3.2.x, seems to cause issues with regards to handing out IP's to VM's via DHCP, packets possibly being dropped, and oddities arising such as the metadata service not functioning when using KVM, but then does in fact work when using QEMU, as well as VM's not being routable or responding to pings.

It turns out that from Ubuntu 12.04.2 onwards, the OS now comes with a hardware enablement package added (https://wiki.ubuntu.com/Kernel/LTSEnablementStack) that automatically enables the 3.5+ kernel by default (https://wiki.ubuntu.com/PrecisePangolin/ReleaseNotes/UbuntuDesktop#PrecisePangolin.2BAC8-ReleaseNotes.2BAC8-CommonInfrastructure.Ubuntu_Kernel_3.5.0-23.35).

Searching around launchpad there seems to be some open tickets with OpenStack that date as far back as August 2012 around issues with VM networking as a result of using kernels from 3.3 onwards, but not in 3.2*. Here are a couple: https://lists.launchpad.net/openstack/msg15636.html and https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1035172

To clarify: the usage of Ubuntu 12.04.2 is fine, so long as its with a 3.2.x kernel - ie if the base install is either the original 12.04 or 12.04.1, and then it was upgraded to 12.04.2 where the kernel is 3.2.x, then OpenStack works just fine.

I have the Ubuntu 12.04.2 & 3.2.x kernel combo working right now and these are the latest versions via a dist-upgrade of a base install of 12.04 OS as of 3/20/13

**Comment by breu** [comment]
This lp bug may also be related: https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1029430

**Comment by mancdaz** [comment]
It seems a fix was released in:

2012.2.3 (folsom)
2013.1 (grizzly)

also in quantal (fix released 25th Apr 2013)
