### ISSUE TITLE
[DE54]: Package upgrade kicks controller back to available nodes

### ISSUE THREAD

**Issue by john5223** [rcbops/opencenter#464]
Run happy path.

Do a package upgrade from: 
http://build.monkeypuppetlabs.com/proposed-packages/rcb-utils/ 

and the controller gets kicked back to available nodes and is locked. 

This gist shows the controller node after the package upgrade:
https://gist.github.com/john5223/b7b689499695cb9fa57b

**Comment by rpedde** [comment]
Would suggest that moving server to service container only happen on initial node create, not ever time it whoamis.  In addition, would probably make sense to lock the server, if it's not already locked.

**Comment by jacobwagner** [comment]
update: seeing this on centos as well.
