### ISSUE TITLE
[DE63]: agent update adventure is broken

### ISSUE THREAD

**Issue by breu** [rcbops/opencenter#471]
Throws a traceback

"GET /admin/tasks/60 HTTP/1.1" 200 1721
got result back: {u'status': 200, u'message': u'success', u'task': {u'completed': 1364403466, u'expires': 1364403465, u'submitted': 1364403435, u'id': 60, u'parent_id': 59, u'state': u'done', u'node_id': 7, u'result': {u'result_str': u'dispatch error', u'result_code': 254, u'result_data': u'[\'Traceback (most recent call last):\n\', \'  File "/usr/lib/python2.6/site-packages/opencenteragent/**init**.py", line 78, in run\n    data[\\'output\\'] = output_handler.dispatch(data[\\'input\\'])\n\', \'  File "/usr/lib/python2.6/site-packages/opencenteragent/modules/output_manager.py", line 209, in dispatch\n    result = fn(input_data)\n\', \'  File "/usr/share/opencenter-agent/plugins/output/plugin_packages.py", line 272, in dispatch\n    return f(input_data)\n\', \'  File "/usr/share/opencenter-agent/plugins/output/plugin_packages.py", line 128, in do_updates\n    return self.script.run_env("update-package.sh", env, "")\n\', \'  File "/usr/share/opencenter-agent/plugins/lib/bashscriptrunner.py", line 79, in run_env\n    env=env)\n\', \'  File "/usr/share/opencenter-agent/plugins/lib/bashscriptrunner.py", line 113, in **init**\n    os.execvpe(cmd[0], cmd, env)\n\', \'  File "/usr/lib64/python2.6/os.py", line 353, in execvpe\n    _execvpe(file, args, env)\n\', \'  File "/usr/lib64/python2.6/os.py", line 368, in _execvpe\n    func(file, *argrest)\n\', \'TypeError: execve() arg 3 contains a non-string value\n\']'}, u'action': u'do_updates', u'payload': {u'globals': {u'parent_task_id': 59}, u'SLEEP': 30, u'PACKAGE_NAME': u'opencenter-agent', u'timeout': 600, u'DISABLE_RESTART': u'true'}}}

**Comment by mattt416** [comment]
Closing, this was resolved in https://github.com/rcbops/opencenter-agent/pull/214.
