### ISSUE TITLE
[DE67] Chef nodes created are not actual OC agent nodes depending on /etc/hosts

### ISSUE THREAD

**Issue by kstev** [rcbops/opencenter#476]
Going through OpenCenter install.  Everything seems to function normally.  I'm able to move my controller node into "Infrastructure" and OpenCenter is happy.  All nodes are green.  I noticed that all actions were mysteriously fast and that my controller node did not seem to have any OpenStack packages installed.  On the controller node, I run "chef-client" and notice chef was installed but the node was not assigned any roles:

root@srv1:~# chef-client
Starting Chef Client, version 11.2.0
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Compiling Cookbooks...
[2013-04-01T21:23:40+00:00] WARN: Node srv1 has an empty run list.
Converging 0 resources
Chef Client finished, 0 resources updated

So I check chef and find that I have 2 chef nodes created for each OpenCenter agent node:
root@chef-server:~# /opt/chef-server/bin/knife node list
srv1
srv1.blacksheep.com
root@chef-server:~# /opt/chef-server/bin/knife node show srv1
Node Name:   srv1
Environment: _default
FQDN:
IP:          192.168.200.101
Run List:
Roles:
Recipes:
Platform:    ubuntu 12.04
Tags:
root@chef-server:~# /opt/chef-server/bin/knife node show srv1.blacksheep.com
Node Name:   srv1.blacksheep.com
Environment: rpcs
FQDN:
IP:
Run List:    role[ha-controller1]
Roles:
Recipes:
Platform:
Tags:

I believe this is because of my mangled /etc/hosts : 
root@srv1:~# cat /etc/hosts
127.0.0.1       localhost.localdomain   localhost
        srv1.blacksheep.com    srv1

If I fix my /etc/hosts then this does not happen.
root@srv1:~# cat /etc/hosts
127.0.0.1       localhost.localdomain   localhost
192.168.200.101 srv1.blacksheep.com srv1

(remove chef nodes > remove open center node > remove chef and associated files > remove node opencenter files > re-run agent install on node > move node to "Infrastructure") 

root@chef-server:~# /opt/chef-server/bin/knife node list
srv1.blacksheep.com
root@chef-server:~# /opt/chef-server/bin/knife node show srv1.blacksheep.com
Node Name:   srv1.blacksheep.com
Environment: rpcs
FQDN:        srv1.blacksheep.com
IP:          192.168.200.101
Run List:    role[ha-controller1]
Roles:       ha-controller1, base, mysql-master, rabbitmq-server, keystone, keystone-api, glance-setup, glance-registry, glance-api, nova-setup, nova-network-controller, nova-scheduler, nova-api-ec2, nova-api-os-compute, cinder-setup, cinder-api, cinder-scheduler, nova-cert, nova-vncproxy, horizon-server, openstack-ha
Recipes:     osops-utils::packages, openssh, ntp, sosreport, rsyslog::default, hardware, osops-utils::default, mysql-openstack::server, erlang::default, rabbitmq-openstack::server, keystone::server, keystone::keystone-api, glance::setup, glance::registry, glance::api, nova::nova-setup, nova-network::nova-controller, nova::scheduler, nova::api-ec2, nova::api-os-compute, cinder::cinder-setup, cinder::cinder-api, cinder::cinder-scheduler, nova::nova-cert, nova::vncproxy, mysql::client, mysql::ruby, horizon::server, openstack-ha::default
Platform:    ubuntu 12.04
Tags:

My hostname remained the same throughout : 
root@srv1:~# hostname
srv1.blacksheep.com
root@srv1:~# cat /etc/hostname
srv1.blacksheep.com
root@srv1:~# hostname -s
srv1

The only change was to /etc/hosts

**Comment by claco** [comment]
Actually, this isn't necessarily a hosts problem, but a chef-install problem with client.rb when the hostname changes.
We should be specifying node_name in client.rb so it's not effected by hostname/hosts shenanigans.

See: https://github.com/rcbops/opencenter-agent/issues/229

**Comment by claco** [comment]
Fixed in https://github.com/rcbops/opencenter-agent/pull/242
