### ISSUE TITLE
[DE72]: Sometimes have to rerun install --role=server

### ISSUE THREAD

**Issue by retreved** [rcbops/opencenter#481]
I have had occasional problems after installin role--server and role=dashboard where I have to rerun --role=server due to 403 errors returned from opencentercli.  All nodes with the agent check in and show green.

root@opencenter:~# opencentercli  node list

id |name          |task |adventure |attrs                         |facts                         |
reverter_
---|--------------|-----|----------|------------------------------|------------------------------|

1 |workspace     |None |None      |{u'display_name': u'Worksp... |{u'backends': [u'container... |
2 |unprovisioned |None |None      |{u'display_name': u'Availa... |{u'parent_id': 1, u'backen... |
3  |support       |None |None      |{u'display_name': u'Servic... |{u'parent_id': 1, u'backen... |
4  |opencenter    |None |None      |{u'opencenter_agent_action... |{u'parent_id': 3, u'backen... |
5  |chef-server   |None |None      |{u'opencenter_agent_action... |{u'parent_id': 2, u'backen... |
6  |compute1      |None |None      |{u'converged': True, u'las... |{u'parent_id': 2, u'backen... |
7  |compute2      |None |None      |{u'converged': True, u'las... |{u'parent_id': 2, u'backen... |
8  |controller    |None |None      |{u'converged': True, u'las... |{u'parent_id': 2, u'backen... |
# root@opencenter:~# opencentercli adventure execute 5 2

Executing Adventure 2, Install Chef Server on Node 5, chef-server
2013-04-02 16:48:00,230 - opencenter.adventure - WARNING - status code 403 on post

   Manually restarting the services does not fix the problem.  The workaround is to rerun './install.sh role=server'.

**Comment by galstrom21** [comment]
@retreved: can you provide a better view of the steps taken to reproduce this? Did it look like this?
1. Install.sh with --role=server on node4
2. install.sh with --role=dashboard on node4
3. Install.sh with --role=agent on node{5,6,7,8}
4. opencentercli adventure execute 5 2

**Comment by kstev** [comment]
According to https://privatecloudforums.rackspace.com/viewtopic.php?f=4&t=401, this happens when you install the agent role on the OpenCenter server node.

confirmed:
[root@ocsrv01 ~]# curl -s -L http://sh.opencenter.rackspace.com/install.sh | bash -s - --role=server --ip=166.78.178.73
[root@ocsrv01 ~]# curl -s -L http://sh.opencenter.rackspace.com/install.sh | bash -s - --role=dashboard --ip=166.78.178.73
[root@ocsrv01 ~]#curl -s -L http://sh.opencenter.rackspace.com/install.sh | bash -s - --role=agent --ip=166.78.178.73

[root@chefsrv01 ~]# curl -s -L http://sh.opencenter.rackspace.com/install.sh | bash -s - --role=agent --ip=166.78.178.73

[root@ocsrv01 ~]# opencentercli adventure execute 5 2
Executing Adventure 2, Install Chef Server on Node 5, chefsrv01
2013-04-05 23:11:23,747 - opencenter.adventure - WARNING - status code 403 on post

**Comment by galstrom21** [comment]
@kstev the server install automatically does the agent as well.. So you do not need to run the last install command.. Can you verify that resolves the issue?

**Comment by galstrom21** [comment]
All you need on the server is the server role and the dashboard role.

**Comment by kstev** [comment]
Correct. That's what I've been telling folks. Perhaps this is not a 'bug' but evidence that the install instructions are not clear or that there should be some sort of sanity check if you try to run the agent role install on the 1st and only server node?

**Comment by galstrom21** [comment]
@kstev: which documentation is instructing you to run the agent install on the server node? Let me know and Ill file a docbug.

**Comment by ddaeschler** [comment]
In this documentation:  http://www.rackspace.com/knowledge_center/article/installing-rackspace-private-cloud-software

Immediately after the "Install the OpenCenter User Interface" section, under "Install OpenCenter Agent" the instructions are simply:

"Run the following curl command on each node that will be managed with OpenCenter:"

I think that is what is tripping people up. Adding something like "(note it is not necessary to install the OpenCenter Agent on the OpenCenter server node)" may resolve the problem.

**Comment by galstrom21** [comment]
@ddaeschler: thanks for the link.. I have filed a docbug to amend the guide with a note about the agent already being installed on the server.
