### ISSUE TITLE
[DE73]: Install script bug

### ISSUE THREAD

**Issue by rpawlik** [rcbops/opencenter#482]
When installing the OC agent using the bash installer, it's not parsing options correctly:

root@chef-server:~# ./install.sh --role=agent -i 10.240.0.243
Invalid IP specified - exiting
usage: ./install.sh options

This script will install opencenter packages.

OPTIONS:
  -h --help  Show this message
  -v --verbose Verbose output
  -V --version Output the version of this script

ARGUMENTS:
  -r --role=[agent | server | dashboard]
         Specify the role of the node - defaults to "agent"
  -i --ip=<Opencenter Server IP>
         Specify the Opencenter Server IP - defaults to "0.0.0.0"
  -p --password=<Opencenter Server IP>
         Specify the Opencenter Server Password - defaults to "password"
  -rr --rerun
         Removes packages and reinstalls them
         Can be used to adjust IP/password information

-i=10.240.0.243 and --ip=10.240.0.243 works.

**Comment by hughsaunders** [comment]
This is a help string bug, it is expected that short args require equals.

**Comment by hughsaunders** [comment]
After a small kerfuffle with RallyIDs, this is now fixed in sprint.
