### ISSUE TITLE
[DE74]: Create Nova cluster fails

### ISSUE THREAD

**Issue by rpawlik** [rcbops/opencenter#483]
root@opencenter-server:~# opencentercli adventure execute 1 3
Executing Adventure 3, Create Nova Cluster on Node 1, workspace
chef_server: Chef Server
chef_server (interface) REQUIRED > eth0
invalid literal for int() with base 10: 'eth0'

Is it expecting a number? If so, what number? I would think it's looking for the name of the interface (eth0, eth1, etc.).

**Comment by galstrom21** [comment]
```
$ opencentercli node list
id |name                          |task |adventure |attrs                         |facts                         |
---|------------------------------|-----|----------|------------------------------|------------------------------|
1  |workspace                     |None |None      |{u'display_name': u'Worksp... |{u'backends': [u'container... |
2  |unprovisioned                 |None |None      |{u'display_name': u'Availa... |{u'parent_id': 1, u'backen... |
3  |support                       |None |None      |{u'display_name': u'Servic... |{u'parent_id': 1, u'backen... |
4  |s1-opencenter-client2.open... |None |None      |{u'converged': True, u'las... |{u'parent_id': 2, u'backen... |
5  |s1-opencenter-client1.open... |None |None      |{u'converged': True, u'las... |{u'parent_id': 2, u'backen... |
6  |s1-opencenter-server.openc... |None |None      |{u'opencenter_agent_action... |{u'parent_id': 3, u'backen… |

$ opencentercli node show 3
name        : "support"
task        : null
adventure   : null
attrs       : {
                  "display_name": "Service Nodes",
                  "locked": true
              }
facts       : {
                  "backends": [
                      "container",
                      "node"
                  ],
                  "parent_id": 1
              }
id          : 3

$ opencentercli node adventure list 1
Adventures that may be executed against node 1, support:
None

$ opencentercli adventure execute 1 3
Executing Adventure 3, Create Nova Cluster on Node 1, workspace
chef_server: Chef Server
chef_server (interface) REQUIRED > eth0
invalid literal for int() with base 10: 'eth0'
```

# 

This is because you are trying to create a nova cluster before creating a chef-server. The solver is attempting to ask for the id of the server which would provide the chef-server interface (which does not exist at this point). 

Also note that the "create nova cluster" adventure is not available on node 1

Create a chef-server on one of your available nodes, then once that is completed you can execute the 'create nova cluster' adventure.

# 

```
$ opencentercli adventure execute 5 2
Executing Adventure 2, Install Chef Server on Node 5, s1-opencenter-client1.opencenter.com
```

-- wait for task completion --

```
$ opencentercli node adventure list 1
Adventures that may be executed against node 1, workspace:
id |criteria                      |name                |
---|------------------------------|--------------------|
3  |(id = 1) and (ifcount('che... |Create Nova Cluster |
```

**Comment by rpawlik** [comment]
From looking back through my output, it looks like I ran the chef-server install twice. The first time it appears it was successful. The second time it tried to roll it back. Is this the expected behavior?

1  |1364961578 |1364962286 |1364961476 |None   |done  |opencenter-server |adventurate                  |
2  |1364961575 |1364961506 |1364961476 |1      |done  |chef-server       |install_chef_server          |
3  |1364961580 |1364962352 |1364961542 |None   |done  |opencenter-server |adventurate                  |
4  |1364961544 |1364961573 |1364961543 |3      |done  |chef-server       |install_chef_server          |
5  |1364961556 |1364961579 |1364961549 |3      |done  |chef-server       |download_cookbooks           |
6  |1364961575 |1364961589 |1364961559 |3      |done  |chef-server       |rollback_install_chef_server |

**Comment by galstrom21** [comment]
So running install_chef_server adventure once it has been already run successfully, would probably result in a roll back.. This is protected against in the UI, and once the adventure has been run, it is not in the list of available adventures for that node.

**Comment by rpawlik** [comment]
So it rolled the chef install back after trying to run it again? In other words, I had a chef server configured after the first time I ran it, but when I ran it again it rolled back the original changes and so I no longer have a chef server? That seems like something that should be checked for and prevented when using the CLI as well.

**Comment by galstrom21** [comment]
@rpawlik: there is two issues here.. 
1. is the idempotency of the install_chef_server script (which is a bug). 
2. is around making the cli behave similarly to the UI (enforcing adventure criteria in the non-admin api).

#1 has been filed as a defect rcbops/opencenter-agent#243
#2 needs more discussion..
