### ISSUE TITLE
[DE75] Creating controller node fails

### ISSUE THREAD

**Issue by rpawlik** [rcbops/opencenter#484]
root@opencenter-server:~# opencentercli task logs 11
=== Logs for task 11: needsrekick.openstack.com > install_chef ===
1.2.0/distro/debian/etc/init.d/chef-client /etc/init.d/chef-client
- chmod +rx /etc/init.d/chef-client
- mkdir -p /var/log/chef
- chef-client
  [2013-04-03T04:14:37+00:00] INFO: **\* Chef 11.2.0 ***
  [2013-04-03T04:14:37+00:00] INFO: [inet6] no default interface, picking the first ipaddress
  [2013-04-03T04:14:38+00:00] INFO: Client key /etc/chef/client.pem is not present - registering
# 
# Chef encountered an error attempting to create the client "needsrekick"

[2013-04-03T04:14:38+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2013-04-03T04:14:38+00:00] FATAL: Chef::Exceptions::InvalidPrivateKey: The file /etc/chef/validation.pem or :raw_key option does not contain a correctly formatted private key.
The key file should begin with '-----BEGIN RSA PRIVATE KEY-----' and end with '-----END RSA PRIVATE KEY-----'

=== End of Logs ===
root@opencenter-server:~# opencentercli node list
id |name                      |task |adventure |attrs                         |facts                         |
---|--------------------------|-----|----------|------------------------------|------------------------------|
1  |workspace                 |None |None      |{u'display_name': u'Worksp... |{u'backends': [u'container... |
2  |unprovisioned             |None |None      |{u'display_name': u'Availa... |{u'parent_id': 1, u'backen... |
3  |support                   |None |None      |{u'display_name': u'Servic... |{u'parent_id': 1, u'backen... |
4  |opencenter-server         |None |None      |{u'opencenter_agent_action... |{u'parent_id': 3, u'backen... |
5  |chef-server               |None |None      |{u'opencenter_agent_action... |{u'chef_server_pem': None,... |
6  |needsrekick.openstack.com |None |None      |{u'opencenter_agent_action... |{u'parent_id': 2, u'backen... |
7  |NovaCluster               |None |None      |{u'locked': True}             |{u'nova_dmz_cidr': u'127.0... |
8  |Infrastructure            |None |None      |{u'locked': False}            |{u'osops_public': u'10.240... |
9  |Compute                   |None |None      |{u'locked': True}             |{u'osops_public': u'10.240... |
10 |AZ nova                   |None |None      |{}                            |{u'osops_public': u'10.240... |

root@opencenter-server:~# opencentercli fact list
id |value                         |node                      |key                           |
---|------------------------------|--------------------------|------------------------------|
1  |1                             |unprovisioned             |parent_id                     |
2  |1                             |support                   |parent_id                     |
3  |[u'container', u'node', u'... |workspace                 |backends                      |
4  |[u'container', u'node']       |unprovisioned             |backends                      |
5  |[u'container', u'node']       |support                   |backends                      |
6  |[u'node', u'agent']           |opencenter-server         |backends                      |
7  |3                             |opencenter-server         |parent_id                     |
8  |[u'node', u'agent']           |chef-server               |backends                      |
9  |2                             |chef-server               |parent_id                     |
10 |[u'node', u'agent']           |needsrekick.openstack.com |backends                      |
11 |2                             |needsrekick.openstack.com |parent_id                     |
12 |None                          |chef-server               |chef_server_client_name       |
13 |None                          |chef-server               |chef_server_client_pem        |
14 |None                          |chef-server               |chef_server_uri               |
15 |None                          |chef-server               |chef_server_pem               |
16 |None                          |chef-server               |chef_server_cookbook_channels |
17 |1                             |NovaCluster               |parent_id                     |
18 |10.240.0.0/24                 |NovaCluster               |osops_public                  |
19 |0                             |NovaCluster               |chef_server_consumed          |
20 |10.240.0.0/24                 |NovaCluster               |nova_public_if                |
21 |16                            |NovaCluster               |cpu_allocation_ratio          |
22 |br100                         |NovaCluster               |nova_vm_bridge                |
23 |[u'node', u'container', u'... |NovaCluster               |backends                      |
24 |127.0.0.0/24                  |NovaCluster               |nova_dmz_cidr                 |
25 |False                         |NovaCluster               |nova_use_single_default_ga... |
26 |1                             |NovaCluster               |ram_allocation_ratio          |
27 |test1234                      |NovaCluster               |keystone_admin_pw             |
28 |kvm                           |NovaCluster               |libvirt_type                  |
29 |10.240.0.0/24                 |NovaCluster               |osops_mgmt                    |
30 |eth0                          |NovaCluster               |nova_vm_fixed_if              |
31 |NovaCluster                   |NovaCluster               |chef_environment              |
32 |novalocal                     |NovaCluster               |nova_network_dhcp_name        |
33 |10.240.0.0/24                 |NovaCluster               |nova_vm_fixed_range           |
34 |10.240.0.0/24                 |NovaCluster               |osops_nova                    |
35 |7                             |Infrastructure            |parent_id                     |
36 |[u'node', u'container', u'... |Infrastructure            |backends                      |
37 |nova-controller-master        |Infrastructure            |nova_role                     |
38 |False                         |Infrastructure            |ha_infra                      |
39 |7                             |Compute                   |parent_id                     |
40 |[u'node', u'container', u'... |Compute                   |backends                      |
41 |nova-compute                  |Compute                   |nova_role                     |
42 |9                             |AZ nova                   |parent_id                     |
43 |nova                          |AZ nova                   |nova_az                       |
44 |[u'node', u'container', u'... |AZ nova                   |backends                      |

Let me know if there's any other logs you need.

**Comment by mattt416** [comment]
Hello @rpawlik,

What jumps out at me here is that your chef-server facts are all empty:

```
12 |None |chef-server |chef_server_client_name |
13 |None |chef-server |chef_server_client_pem |
14 |None |chef-server |chef_server_uri |
15 |None |chef-server |chef_server_pem |
16 |None |chef-server |chef_server_cookbook_channels |
```

You will see empty chef-server facts if the chef-server uninstall adventure is executed (or a rollback occurs), however it will also remove the chef-server backend from your chef-server node which will prevent chef-client from being installed on nodes without a chef-client backend.

Is it possible to provide us with information as to why your chef-server was uninstalled/removed, and also provide us with details on opencenter-server/agent/client versions present in your environment?  Can you also show us your chef-client configuration on needsrekick?

Thanks!

-Matt

**Comment by rpawlik** [comment]
I think it's related to this:

https://github.com/rcbops/opencenter-agent/issues/243

I ran the chef-server install twice on accident which rolled back the original install.
