### ISSUE TITLE
[DE106]: Node does not re-register if deleted

### ISSUE THREAD

**Issue by devx** [rcbops/opencenter#503]
The opencenter agent does not re-register if the node is deleted from opencenter.

**Comment by hughsaunders** [comment]
This is expected, the agent stores it's node ID in a file, by default this is /etc/opencenter/hostid. If that file is removed then the agent will re-register. However what is missing is that the agent does not detect that the node it is installed on has been deleted by the server. It should detect this, and exit with a message saying that the node has been deleted and file x should be deleted if re-registration is required.

**Comment by devx** [comment]
Thanks for the information, it works as you explained. Maybe documentation, or an error/warning message about not being able to register would suffice.

Thanks!

**Comment by hughsaunders** [comment]
Fixed in: https://github.com/rcbops/opencenter-agent/commit/8e78e0b33917517eefc4eefefed66ecd4017c426
