### ISSUE TITLE
[DE139]: i386 repository missing packages

### ISSUE THREAD

**Issue by cfarquhar** [rcbops/opencenter#507]
We received a report that a customer was unable to install OpenCenter on 32 bit CentOS 6.  Looking at the primary.xml from http://packages.opencenter.rackspace.com/stable/rpm/RedHat/6/i386/ , I see only one package listed.  The equivalent x86_64 repository has several hundred packages.  Please verify whether this is due to 32 bit being unsupported or a problem with the repository. 

Additional information can be found at https://privatecloudforums.rackspace.com/viewtopic.php?f=4&t=461 .

**Comment by breu** [comment]
Hello @cfarquhar 

i386 is unsupported by our current cookbooks however the work on our grizzly branch may be useful in the future when we move all of the Rackspace specific bits (i.e. monitoring, etc) into side-car cookbooks that will run alongside the vanilla OpenStack chef recipes.
